version: "2"
services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    command: [nginx-debug, '-g', 'daemon off;']
  node:
    image: node:18-alpine
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app/
    ports:
      - "8000:8000"
    command: "npm run dev"
